version: '3.8'
services:
  mysql:
    container_name: mysql
    image: 'mysql:8.0.19'
    ports:
      - '3306:3306'
    env_file:
      - env/mysql.env
      - env/docker-compose.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bookstore-backend-network

  spring-boot-backend:
    image: eclipse-temurin:23-jdk-alpine
    container_name: spring_app
    working_dir: /app
    env_file:
      - ./env/springboot-backend.env
    volumes:
      - .:/app  # Mount toàn bộ code vào container
      - ~/.m2:/root/.m2 # Bind mount cache Maven
    ports:
      - "8181:8181"
    command: [ "./mvnw", "spring-boot:run" ]
    networks:
      - bookstore-backend-network
    depends_on:
      - mysql

  spring-boot-test:
    image: eclipse-temurin:23-jdk-alpine
    container_name: spring_app_test
    working_dir: /app
    env_file:
      - ./env/springboot-backend.env
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: [ "./mvnw", "test" ]
    networks:
      - bookstore-backend-network

volumes:
  mysql_data:

networks:
  bookstore-backend-network: