version: '3.8'
services:
  mysql:
    container_name: mysql
    image: 'mysql:8.0.19'
    ports:
      - '3306:3306'
    env_file:
      - env/mysql.env
      - env/docker-compose.env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: