version: '3.8'
services:
  mysql:
    container_name: mysql
    image: 'mysql:8.0.19'
    ports:
      - '3306:3306'
    env_file:
      - env/mysql.env
      - env/docker-compose.env
    volumes:
      - mysql_data:/var/lib/mysql

  springboot:
    build:
      context: ./back-end
      dockerfile: Dockerfile.production
    container_name: springboot
    env_file:
      - ./env/backend.production.env
    ports:
      - "8181:8181"
    depends_on:
      - mysql

  nginx:
    build:
      context: ./front-end
      dockerfile: Dockerfile.production
    container_name: nginx
    environment:
      - DOMAIN_BACK_END=back-end.anhtuan.online
      - DOMAIN_FRONT_END=front-end.anhtuan.online
    volumes:
      - /etc/letsencrypt/live/front-end.anhtuan.online/fullchain.pem:/etc/nginx/ssl/front-end/fullchain.pem
      - /etc/letsencrypt/live/front-end.anhtuan.online/privkey.pem:/etc/nginx/ssl/front-end/privkey.pem
      - /etc/letsencrypt/live/back-end.anhtuan.online/fullchain.pem:/etc/nginx/ssl/back-end/fullchain.pem
      - /etc/letsencrypt/live/back-end.anhtuan.online/privkey.pem:/etc/nginx/ssl/back-end/privkey.pem
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - springboot

volumes:
  mysql_data:
