server:
  port: 0
spring:
  application:
    name: BackEnd-BookStore
  servlet:
    context-path: /api
  datasource:
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/bookstore
