FROM node:lts-alpine as build
# Set working directory
WORKDIR /app
#
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . .
ENV CI=true
ENV PORT=3000
RUN npm run build
# 2. For Nginx setup
FROM nginx:alpine
# Copy config nginx
COPY .nginx/nginx.conf /etc/nginx/nginx.conf
# Copy static assets from builder stage
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80/tcp
# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]