version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: react-app
    ports:
    - "3000:80" # map 80 in container => 3000 in local
    volumes:
      - ./dist:/app/dist # bind mount đến thư mục gốc trong project để check
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiNjJjMWNiYTQwYjlhNjJjZmVjMTMzYjZhMDAyZjM2NmIiLCJ0IjoiNzQ3OGM2YjMtZjZjOC00NGJmLTkyMTctNTVlYzUyZmQ1MzVmIiwicyI6IllXSXdOREF3TmpZdFpqUTNNeTAwT1RWbUxUa3haV0l0T0RZNFlqRmlNREk0WldNdyJ9