FROM node:lts-alpine AS react-build
# Set working directory
WORKDIR /app
#
COPY . .
RUN npm install
ENV CI=true
ENV PORT=3000
RUN npm run build
# 2. For Nginx setup
FROM nginx:alpine AS deploy
# Copy config nginx
COPY .nginx/nginx.develop.conf /etc/nginx/nginx.conf
# Copy static assets from builder stage
COPY --from=react-build /app/dist /usr/share/nginx/html
EXPOSE 80/tcp
# Containers run nginx with global directives and daemon off
CMD [ "nginx", "-g", "daemon off;" ]