# Dockerfile.agent
FROM jenkins/agent

USER root
RUN apt update && apt install -y openjdk-17-jdk curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/jenkins/agent
COPY agent/start-agent.sh start-agent.sh
RUN chmod +x start-agent.sh && chown jenkins:jenkins start-agent.sh
USER jenkins

CMD ["sh", "./start-agent.sh"]
