server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: BackEnd-BookStore
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bookstore}
  data:
    redis:
      port: 6379
      host: localhost
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
app:
  jwt-key: 1ytvns7A2HHo2GUQ2d82xS2I7dRyWWv1BTU51Ve+il0=
  aws:
    access-key-id: ${SPRING_AWS_ACCESS_KEY_ID:_}
    secret-access-key: ${SPRING_AWS_SECRET_ACCESS_KEY:_}
    bucket:
      name: nqat.bookstore.bucket
      request-timeout: 3600 # in seconds
  temp-folder: D:\tmp

