server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: BackEnd-BookStore
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root  # Lấy từ biến môi trường, nếu không có thì mặc định là "admin"
    password: 12345678
    url: jdbc:mysql://localhost:3306/book-store
  data:
    redis:
      port: 6379
      host: localhost
  batch:
    jdbc:
      initialize-schema: always
#  batch:
#    datasource:
#      url: jdbc:mysql://localhost:3306/batch_db
#      username: root
#      password: 12345678
#      jdbc:
#        initialize-schema: never
app:
  jwt-key: 1ytvns7A2HHo2GUQ2d82xS2I7dRyWWv1BTU51Ve+il0=
  aws:
    access-key-id: ${SPRING_AWS_ACCESS_KEY_ID:<Nhập Key ID vào đây>}
    secret-access-key: ${SPRING_AWS_SECRET_ACCESS_KEY:<Nhập Secret Key Id vào đây>}
    bucket:
      name: nqat.bookstore.bucket
      request-timeout: 3600 # in seconds

