server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: BackEnd-BookStore
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root  # Lấy từ biến môi trường, nếu không có thì mặc định là "admin"
    password: 12345678
    url: jdbc:mysql://localhost:3306/book-store

app:
  jwt-key: 1ytvns7A2HHo2GUQ2d82xS2I7dRyWWv1BTU51Ve+il0=
